### ISSUE TITLE
Railsルーティングの説明(description)に句点が一つない

### ISSUE THREAD

**Issue by cloneko** [yasslab/railsguides.jp#383]
https://github.com/yasslab/railsguides.jp/blob/master/guides/source/ja/documents.yaml
の

Railsルーティングの説明(description)の「Railsのルーティング機能について解説します」のあとに句点(。)が無い。

```yaml
     name: Rails ルーティング
      url: routing.html
      description: Railsのルーティング機能について解説しますRailsアプリケーションで行われているルーティングのしくみについて理解したい場合は、ここからお読みください。
```
は
```yaml
     name: Rails ルーティング
      url: routing.html
      description: Railsのルーティング機能について解説します。Railsアプリケーションで行われているルーティングのしくみについて理解したい場合は、ここからお読みください。
```
が適切だと思います。
